#!/bin/bash

# Demo script for Multi-Orchestrator with NLP Understanding

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Multi-Orchestrator with NLP Understanding - Demo         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This demo shows how the orchestrator now understands natural"
echo "language instead of just matching keywords."
echo ""
echo "Press Enter to start the demo..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Example 1: Natural Language - 'create a webserver with auth'"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "The orchestrator will:"
echo "  1. Classify intent: create_handler"
echo "  2. Extract entities: handler_name='auth', component='webserver'"
echo "  3. Generate appropriate Go code"
echo ""
echo "Try it yourself by running:"
echo "  ./cmd/multi_orchestrator/multi_orchestrator"
echo ""
echo "Then type: create a webserver with authentication handler"
echo ""
echo "Press Enter to see more examples..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Example 2: Database Creation"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Natural language: 'I need a database for storing users'"
echo ""
echo "The orchestrator will:"
echo "  1. Classify intent: create_database"
echo "  2. Extract entities: database_name='users'"
echo "  3. Generate server with database integration"
echo ""
echo "Press Enter to see more examples..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Example 3: Complex Command"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Natural language: 'build me a Go API server with JWT authentication'"
echo ""
echo "The orchestrator will:"
echo "  1. Classify intent: create_handler or add_feature"
echo "  2. Extract entities: component='API', feature='JWT authentication'"
echo "  3. Generate appropriate code structure"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Key Improvements                                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Intent Classification - Understands WHAT you want to do"
echo "✅ Entity Extraction - Identifies names, types, parameters"
echo "✅ Semantic Parsing - Builds structured command representation"
echo "✅ Natural Language - Write commands as you would speak them"
echo "✅ Fallback Support - Still works with keyword-based commands"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Ready to try it yourself?"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Run: ./cmd/multi_orchestrator/multi_orchestrator"
echo ""
echo "Try these commands:"
echo "  • create a webserver with authentication handler"
echo "  • I want to build an API with a database called users.db"
echo "  • make me a Go server with JWT support"
echo "  • build a REST API with logging middleware"
echo ""
